import streamlit as st
#st.set_page_config(page_title="My Webpage", page_icon=":tada:", layout="wide",initial_sidebar_state="collapsed")
from pages.home import show_home
from pages.about import about
from pages.projects import projects
from pages.exp import experience
from pages.education import education
from pages.cert import certifications
from pages.contact import contact_form
from pages.social import media